nombre : Crear APK de Android

en :
  empujar :
    ramas : [ "principal", "maestro" ]
  flujo_de_trabajo :

empleos :
  construir :
    se ejecuta en : ubuntu-latest

    pasos :
      - nombre : Repositorio de Checkout
        usos : actions/checkout@v4

      - nombre : Descomprimir ZIP si fue subido como archivo
        correr : |
          ZIP_FILE=$(find . -maxdepth 2 -name "*.zip" | head -n 1)
          si [ -n "$ZIP_FILE" ]; entonces
            echo "Descomprimiendo $ZIP_FILE..."
            descomprimir -o "$ARCHIVO_ZIP"
          fi
      - nombre : Configurar Java JDK 17
        usos : actions/setup-java@v4
        con :
          versión de java : ' 17 '
          distribución : ' temurin '

      - nombre : Configurar Gradle
        Usos : gradle/actions/setup-gradle@v3

      - nombre : Compilador APK de Android
        ejecutar : gradle:app:assembleDebug --no-daemon

      - nombre : Guardar APK como Artefacto
        usos : actions/upload-artifact@v4
        con :
          nombre : TVA_Digital_APK
          ruta : app/build/outputs/apk/debug/app-debug.apk
